[workspace]
members = [
    "node",
    "pallets/template",
    "pallets/simple-pallet",
    "pallets/storage-example",
    "pallets/pallet-debug",
    "runtime",
]
resolver = "2"
[profile.release]
panic = "unwind"
